apiVersion: v1
kind: ConfigMap
metadata:
  name: palindrome-python-code
  namespace: team-five
data:
  app.py: |
    from flask import Flask, request, jsonify
    from prometheus_client import Counter, generate_latest
    import re
    import os

    app = Flask(__name__)

    # Prometheus metrics
    request_counter = Counter('python_requests_total', 'Total requests', ['endpoint'])

    def is_palindrome(text):
        """Check if alphanumeric text equals its reverse"""
        if not text:
            return False
        
        # Keep only alphanumeric characters and lowercase
        alphanumeric = re.sub(r'[^a-z0-9]', '', text.lower())
        
        if not alphanumeric:
            return False
        
        # Check if it's a palindrome
        return alphanumeric == alphanumeric[::-1]

    @app.route('/healthz', methods=['GET'])
    def health():
        request_counter.labels(endpoint='healthz').inc()
        return jsonify({"ok": True})

    @app.route('/metrics', methods=['GET'])
    def metrics():
        return generate_latest()

    @app.route('/op', methods=['POST'])
    def op():
        request_counter.labels(endpoint='op').inc()
        
        data = request.get_json()
        if not data or 'text' not in data:
            return jsonify({"key": "palindrome", "value": False, "cache_hit": False})
        
        text = data.get('text', '')
        palindrome = is_palindrome(text)
        
        return jsonify({
            "key": "palindrome",
            "value": palindrome,
            "cache_hit": False
        })

    if __name__ == '__main__':
        port = int(os.getenv('PORT', 8085))
        app.run(host='0.0.0.0', port=port)
  requirements.txt: |
    flask==3.0.0
    prometheus-client==0.19.0
    gunicorn==21.2.0
---
apiVersion: v1
kind: Service
metadata:
  name: palindrome-python
  namespace: team-five
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8085"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: palindrome-python
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8085
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: palindrome-python
  namespace: team-five
spec:
  replicas: 2
  selector:
    matchLabels:
      app: palindrome-python
  template:
    metadata:
      labels:
        app: palindrome-python
    spec:
      containers:
      - name: palindrome
        image: python:3.11-slim
        ports:
        - containerPort: 8085
        env:
        - name: PORT
          value: "8085"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8085
          initialDelaySeconds: 20
          periodSeconds: 5
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        volumeMounts:
        - name: app-code
          mountPath: /app
        command: ["/bin/sh", "-c"]
        args:
          - |
            pip install --no-cache-dir -r /app/requirements.txt && \
            exec gunicorn --bind 0.0.0.0:8085 --workers 2 --threads 2 --chdir /app app:app
      volumes:
      - name: app-code
        configMap:
          name: palindrome-python-code
